- README.md
> Fix list indentation in README.

- python/lsst/ci/middleware/display.py
- python/lsst/ci/middleware/mock_dataset_maker.py
- python/lsst/ci/middleware/repo_data.py
- tests/test_mock_storage_class.py
> DM-39605: Use butler.dimensions rather than butler.registry.dimensions

- data/SConscript
- doc/changes/DM-39672.feature.md
- python/lsst/ci/middleware/output_repo_tests.py
- python/lsst/ci/middleware/scons.py
- tests/test_rc2_outputs.py
> DM-39672: add forced failure and rescue tests

- python/lsst/ci/middleware/repo_data.py
> DM-39876: Import pydantic.v1 if we have pydantic v2

- .github/workflows/do_not_merge.yaml
- mypy.ini
- python/lsst/ci/middleware/repo_data.py
- tests/test_mock_storage_class.py
- types.txt
> DM-40002: Support pydantic v1 and v2

- doc/changes/DM-37163.feature.rst
- tests/test_prod_outputs.py
> DM-37163: A manifest checker on the workflow output data

- python/lsst/ci/middleware/mock_dataset_maker.py
> DM-41191: Modernize pipeline-analysis interface calls.

- python/lsst/ci/middleware/__main__.py
- python/lsst/ci/middleware/mock_dataset_maker.py
- python/lsst/ci/middleware/output_repo_tests.py
- python/lsst/ci/middleware/repo_data.py
- tests/test_mock_storage_class.py
> DM-41116: Use Butler.from_config to instantiate butler

- python/lsst/ci/middleware/mock_dataset_maker.py
- tests/test_mock_storage_class.py
> DM-34340: Adapt to daf_butler API changes.

- python/lsst/ci/middleware/data/instrument-records.json
- python/lsst/ci/middleware/data/observation-records.json
- python/lsst/ci/middleware/repo_data.py
> DM-42636: Updates for day_obs/group dimensions

- data/SConscript
- python/lsst/ci/middleware/scons.py
> DM-43484: test BPS-style auto-retries

- .github/workflows/rebase_checker.yaml
- pyproject.toml
- python/lsst/ci/middleware/data/observation-records.json
- requirements.txt
> DM-43101: Add exposure.can_see_sky to record json

- tests/test_prod_outputs.py
> DM-44431: Fix middleware test breakage

- python/lsst/ci/middleware/data/input-dataset-types.json
- python/lsst/ci/middleware/mock_dataset_maker.py
- python/lsst/ci/middleware/repo_data.py
> DM-41326: Avoid using DimensionGraph->DimensionGroup transition tools.

- python/lsst/ci/middleware/scons.py
> DM-46525: Make tests insensitive to --raise-on-partial-outputs default.

- .gitignore
- ups/ci_middleware.table
> DM-47127: Depend on lsst_middleware

- data/SConscript
- tests/test_prod_outputs.py
- tests/test_rc2_outputs.py
> DM-46991: switch to calibrateImage

- .gitignore
- data/SConscript
> DM-42226: No longer forward DAF_BUTLER_PLUGINS in tests

- python/lsst/ci/middleware/output_repo_tests.py
> DM-34875: Update storage class conversion test to reflect pipeline changes.

- python/lsst/ci/middleware/repo_data.py
> DM-38497: Use new bind syntax in expressions

- tests/test_rc2_outputs.py
> DM-49625: Update test to expect new task.

- tests/test_rc2_outputs.py
> DM-49625-v29: Update test to expect new task.

- data/SConscript
- python/lsst/ci/middleware/data/data_ids.ecsv
- python/lsst/ci/middleware/scons.py
- tests/test_rc2_outputs.py
> DM-49949: Add tests for --data-id-table pipetask option.

- pyproject.toml
- python/lsst/ci/middleware/output_repo_tests.py
- tests/test_rc2_outputs.py
> DM-51687: Adjust for change in upstream tasks
